import time
from selenium import webdriver
path = r"C:\Users\Anu\PycharmProjects\pythonProject1\drivers\chromedriver1.exe"

option = webdriver.ChromeOptions()
option.add_argument("--disable-notifications")
driver = webdriver.Chrome(executable_path=path, options=option)
driver.get("https://pharmeasy.in/")
driver.maximize_window()
driver.implicitly_wait(15)


# driver.find_element("xpath", '//span[text()="Hello, Log in"]').click()
# time.sleep(2)
# driver.find_element("xpath", '//input[@placeholder="Enter your phone number"]').send_keys("9113676419")
# time.sleep(2)
# driver.find_element("xpath", '//button[@type="submit"]').click()
# time.sleep(15)
# driver.find_element("xpath", '//button[@type="submit"]').click()
# time.sleep(2)

driver.find_element("xpath", '//span[text()="Lab Tests"]').click()
time.sleep(2)
driver.find_element("xpath", '//a[.="Health Packages"]').click()
time.sleep(2)
driver.find_element("xpath", '//div[.="Diabetes Care"]').click()
time.sleep(2)
driver.find_element("xpath", '//button[.="Select"]').click()
time.sleep(2)
driver.find_element("xpath", '(//p[@class="_39TRp"])[1]').click()
time.sleep(2)
# driver.find_element("xpath", '(//p[@class="_39TRp"])[2]').click()
# time.sleep(2)
# driver.find_element("xpath", '(//p[@class="_39TRp"])[3]').click()
# time.sleep(2)
# driver.find_element("xpath", '(//p[@class="_39TRp"])[4]').click()
# time.sleep(2)
# driver.find_element("xpath", '(//p[@class="_39TRp"])[5]').click()
# time.sleep(2)
# driver.find_element("xpath", '//span[@role="button"]').click()
# time.sleep(2)

# driver.find_element("xpath", '//div[@class="wgp0m"]').click()
# time.sleep(2)
# driver.find_element("xpath", '(//div[.="Test Requirement"])[2]').click()
# time.sleep(2)
# driver.find_element("xpath", '//div[.="Description"]').click()
# time.sleep(2)
# driver.find_element("xpath", '(//button[.="View Cart"])[1]').click()
# time.sleep(2)
# driver.find_element("xpath", '//img[@alt="delete icon"]').click()
# time.sleep(2)
# driver.find_element("xpath", '//div[.="Yes"]').click()
# time.sleep(2)
# driver.find_element("xpath", '//div[.="No"]').click()
# time.sleep(2)
driver.find_element("xpath", '//button[@id="cart-addPatient-Dweb"]').click()
time.sleep(2)
driver.find_element("xpath", '//input[@placeholder="Enter your phone number"]').send_keys("8073603505")
time.sleep(2)
driver.find_element("xpath", '//button[.="Continue"]').click()
time.sleep(25)
driver.find_element("xpath", '//button[.=" CONTINUE"]').click()
time.sleep(2)
driver.find_element("xpath", '//button[@id="cart-addPatient-Dweb"]').click()
time.sleep(2)
driver.find_element("xpath", '(//img[@alt="add icon"])[2]').click()
time.sleep(2)

driver.find_element("xpath", '//input[@id="add-Patient-name"]').send_keys("slfygfghjyh")
time.sleep(2)
driver.find_element("xpath", '//input[@type="number"]').send_keys("88")
time.sleep(2)
driver.find_element("xpath", '//div[@id="add-Patient-gender-0"]').click()
time.sleep(2)
driver.find_element("xpath", '//button[@type="submit"]').click()
time.sleep(2)
driver.find_element("xpath", '(//div[.="+ Add new address"])[1]').click()
time.sleep(2)
driver.find_element("xpath", '//input[@name="contactName"]').send_keys("akha")
time.sleep(2)
driver.find_element("xpath", '//input[@name="pincode"]').send_keys("400001")
time.sleep(2)
driver.find_element("xpath", '//input[@name="flatNumber"]').send_keys("282")
time.sleep(2)
driver.find_element("xpath", '//input[@name="streetName"]').send_keys("mgroad")
time.sleep(2)
driver.find_element("xpath", '//span[.="Home"]').click()
time.sleep(2)
driver.find_element("xpath", '//button[@id="addAddress-saveBtn"]').click()
time.sleep(2)
driver.find_element("id", 'slot-selection-continueBtn-dWeb').click()
time.sleep(2)
driver.find_element("xpath", '//span[.="Pay Cash"]/../../..//input[@type="radio"]').click()
time.sleep(2)
# driver.find_element("xpath", '//span[.="Place Order"]').click()
# time.sleep(2)

# driver.find_element("xpath", '(//img[@alt="add icon"])[2]').click()
# time.sleep(2)


